In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
%matplotlib inline

### number 5: Using the pandas read_csv() method, read the GDP dataset into your notebook as a DataFrame called gdp_df. Take a look at the first 6 rows.

In [6]:
gdp_df = pd.read_csv("../data/gdp_percapita.csv", nrows=6869)

##### tip from Maggie: footnotes begin in row 6869 in this file, add nrows into read_csv code

In [9]:
print(gdp_df.head(6))

  Country or Area  Year        Value  Value Footnotes
0     Afghanistan  2019  2065.036398              NaN
1     Afghanistan  2018  2033.779002              NaN
2     Afghanistan  2017  2058.383832              NaN
3     Afghanistan  2016  2057.062164              NaN
4     Afghanistan  2015  2068.265904              NaN
5     Afghanistan  2014  2102.385234              NaN


### number 6: Repeat for the internet use dataset. Call this DataFrame internet_df. Take a look at the first six rows.

In [8]:
internet_df = pd.read_csv("../data/internet_use.csv", nrows=4496)

##### from watching classmates in setup demo, know to use nrows to avoid footnote error

In [10]:
print(internet_df.head(6))

  Country or Area  Year     Value  Value Footnotes
0     Afghanistan  2014  6.390000              NaN
1     Afghanistan  2013  5.900000              NaN
2     Afghanistan  2012  5.454545              NaN
3     Afghanistan  2011  5.000000              NaN
4     Afghanistan  2010  4.000000              NaN
5     Afghanistan  2009  3.550000              NaN


### number 7: Look at the shape of each DataFrame - how many rows? How many columns?

In [11]:
gdp_df.shape

(6869, 4)

In [12]:
internet_df.shape

(4496, 4)

the GDP table has 6869 rows and 4 columns; 
the internet table has 4496 rows and 4 columns

### number 8: Take a look at the datatypes for the columns in each DataFrame.